name: Zip theme

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Create archive
              run: zip -r feslake-theme.xed README.md theme.json
            - name: Upload artifact
              uses: "actions/upload-artifact@v4"
              with:
                  name: "feslake-theme"
                  path: feslake-theme.xed
